// import { userList } from '../model/Employee';

// export const user_List: userList = [
//   {
//     idUser: 1,
//     firstName: 'Barack',
//     lastName: 'Obama',
//     picture: 'assets/images/barack_obama.jpeg',
//     birthdate: new Date('1961-08-04'),
//     post: 'Ancien Président',
//     birthPlace: 'Honolulu, Hawaii, USA',
//     gender: 'Masculin',
//     nationality: 'Américaine',
//     maritalStatus: 'Marié',
//     children: 2,
//     address: '1600 Pennsylvania Ave NW, Washington, DC 20500, USA',
//     phone: '202-456-1111',
//     email: 'barack.obama@example.com',
//     socialSecurityNumber: '123-45-6789',
//     taxId: '987-65-4321',
//     identificationCardNumber: 'A123456789',
//     issueDate: new Date('2009-01-20'),
//     expirationDate: new Date('2029-01-20'),
//     emergencyContactName: 'Michelle Obama',
//     relationship: 'Épouse',
//     emergencyContactPhone: '202-456-1112',
//     emergencyContactAddress:
//       '1600 Pennsylvania Ave NW, Washington, DC 20500, USA',
//     hireDate: new Date('2008-11-04'),
//     positionLevel: 'Senior',
//     department: 'Politique',
//     salary: 400000, // Salaire fictif
//     benefits: ['Assurance santé', 'Retraite', 'Congés payés'],
//     languages: ['Anglais', 'Espagnol'],
//     skills: ['Leadership', 'Communication', 'Négociation'],
//     performanceRating: 5, // Optionnel
//     status: 'active',
//   },
//   {
//     idUser: 2,
//     firstName: 'Martin',
//     lastName: 'Luther King Jr.',
//     picture: 'assets/images/martin_luther.jpeg',
//     birthdate: new Date('1929-01-15'),
//     post: 'Leader des droits civiques',
//     birthPlace: 'Atlanta, Georgia, USA',
//     gender: 'Masculin',
//     nationality: 'Américaine',
//     maritalStatus: 'Marié',
//     children: 4,
//     address: '1234 Freedom Blvd, Atlanta, GA 30301, USA',
//     phone: '404-555-0199',
//     email: 'martin.luther.king@example.com',
//     socialSecurityNumber: '234-56-7890',
//     taxId: '876-54-3210',
//     identificationCardNumber: 'B123456789',
//     issueDate: new Date('1964-07-02'),
//     expirationDate: new Date('2024-07-02'),
//     emergencyContactName: 'Coretta Scott King',
//     relationship: 'Épouse',
//     emergencyContactPhone: '404-555-0198',
//     emergencyContactAddress: '1234 Freedom Blvd, Atlanta, GA 30301, USA',
//     hireDate: new Date('1955-12-05'),
//     positionLevel: 'Senior',
//     department: 'Droits civiques',
//     salary: 100000, // Salaire fictif
//     benefits: ['Assurance santé', 'Retraite'],
//     languages: ['Anglais', 'Français'],
//     skills: ['Oratoire', 'Leadership', 'Activisme'],
//     performanceRating: 5, // Optionnel
//     status: 'inactive',
//   },
//   {
//     idUser: 3,
//     firstName: 'Nelson',
//     lastName: 'Mandela',
//     picture: 'assets/images/nelson_mandela.jpeg',
//     birthdate: new Date('1918-07-18'),
//     post: 'Ancien Président',
//     birthPlace: 'Mvezo, Afrique du Sud',
//     gender: 'Masculin',
//     nationality: 'Sud-Africaine',
//     maritalStatus: 'Divorcé',
//     children: 6,
//     address: '8115 Vilakazi St, Orlando West, Soweto, Afrique du Sud',
//     phone: '011-555-0199',
//     email: 'nelson.mandela@example.com',
//     socialSecurityNumber: '345-67-8901',
//     taxId: '765-43-2109',
//     identificationCardNumber: 'C123456789',
//     issueDate: new Date('1994-05-10'),
//     expirationDate: new Date('2024-05-10'),
//     emergencyContactName: 'Winnie Mandela',
//     relationship: 'Ex-Épouse',
//     emergencyContactPhone: '011-555-0198',
//     emergencyContactAddress:
//       '8115 Vilakazi St, Orlando West, Soweto, Afrique du Sud',
//     hireDate: new Date('1994-05-10'),
//     positionLevel: 'Senior',
//     department: 'Politique',
//     salary: 250000, // Salaire fictif
//     benefits: ['Assurance santé', 'Retraite', 'Congés payés'],
//     languages: ['Anglais', 'Afrikaans'],
//     skills: ['Leadership', 'Négociation', 'Médiation'],
//     performanceRating: 5, // Optionnel
//     status: 'inactive',
//   },
//   {
//     idUser: 4,
//     firstName: 'Vladimir',
//     lastName: 'Poutine',
//     picture: 'assets/images/vladimir_putin.png',
//     birthdate: new Date('1952-10-07'),
//     post: 'Président',
//     birthPlace: "Leningrad, URSS (aujourd'hui Saint-Pétersbourg, Russie)",
//     gender: 'Masculin',
//     nationality: 'Russe',
//     maritalStatus: 'Marié',
//     children: 2,
//     address: '1, rue du Kremlin, Moscou, Russie',
//     phone: '+7-495-123-4567',
//     email: 'vladimir.putin@example.com',
//     socialSecurityNumber: '456-78-9012',
//     taxId: '654-32-1098',
//     identificationCardNumber: 'D123456789',
//     issueDate: new Date('2000-05-07'),
//     expirationDate: new Date('2024-05-07'),
//     emergencyContactName: 'Lyudmila Ocheretnaya',
//     relationship: 'Ex-Épouse',
//     emergencyContactPhone: '+7-495-123-4568',
//     emergencyContactAddress: '1, rue du Kremlin, Moscou, Russie',
//     hireDate: new Date('1999-12-31'),
//     positionLevel: 'Senior',
//     department: 'Gouvernement',
//     salary: 300000, // Salaire fictif
//     benefits: ['Assurance santé', 'Retraite'],
//     languages: ['Russe', 'Anglais'],
//     skills: ['Politique', 'Stratégie', 'Diplomatie'],
//     performanceRating: 4, // Optionnel
//     status: 'active',
//   },
//   {
//     idUser: 5,
//     firstName: 'Paul',
//     lastName: 'Biya',
//     picture: 'assets/images/paul_biya.png',
//     birthdate: new Date('1933-02-13'),
//     post: 'Président',
//     birthPlace: 'Mvomeka’a, Cameroun',
//     gender: 'Masculin',
//     nationality: 'Camerounaise',
//     maritalStatus: 'Marié',
//     children: 3,
//     address: "Palais de l'Unité, Yaoundé, Cameroun",
//     phone: '+237-222-123-456',
//     email: 'paul.biya@example.com',
//     socialSecurityNumber: '567-89-0123',
//     taxId: '543-21-0987',
//     identificationCardNumber: 'E123456789',
//     issueDate: new Date('1982-11-06'),
//     expirationDate: new Date('2024-11-06'),
//     emergencyContactName: 'Chantal Biya',
//     relationship: 'Épouse',
//     emergencyContactPhone: '+237-222-123-457',
//     emergencyContactAddress: "Palais de l'Unité, Yaoundé, Cameroun",
//     hireDate: new Date('1982-11-06'),
//     positionLevel: 'Senior',
//     department: 'Gouvernement',
//     salary: 250000,
//     benefits: ['Assurance santé', 'Retraite'],
//     languages: ['Français', 'Anglais'],
//     skills: ['Leadership', 'Politique', 'Gestion'],
//     performanceRating: 3,
//     status: 'ACTIVE',
//   },


// ];
